name: Checkers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Install python
        uses: action/setup-python@v2
        with:
          python-version: 3.11
      - name: Install lib
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run black
        run: black --check --diff .
      - name: Run isort
        run: isort --check-only --diff --profile black .